#!/usr/bin/env python3
"""Download Google Fonts (Roboto, Roboto Slab, Material Icons) and self-host them.

Fetches the woff2 files + generates assets/css/fonts.css with local @font-face
rules, so the site no longer contacts fonts.googleapis.com / fonts.gstatic.com
at render time (the LG Muenchen I 2022 Google-Fonts GDPR risk).
"""
import re
import os
import urllib.request

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
KEEP_SUBSETS = {"latin", "latin-ext"}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "assets", "css", "fonts.css")

SOURCES = {
    "text": ("https://fonts.googleapis.com/css2?"
             "family=Roboto:wght@300;400;500;700&"
             "family=Roboto+Slab:wght@100;300;400;500;700&display=swap"),
    "icons": "https://fonts.googleapis.com/icon?family=Material+Icons",
}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read().decode("utf-8")


def download(url, dest):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        data = r.read()
    with open(dest, "wb") as f:
        f.write(data)
    return len(data)


def localize(css, keep_subsets=None):
    """Rewrite gstatic urls to local /assets/fonts, download the files.

    If keep_subsets is given, only keep @font-face blocks whose preceding
    /* subset */ comment is in the set.
    """
    out_lines = []
    # split into (comment, block) chunks for the text css; icons css has no comments
    blocks = re.split(r"(/\*\s*[\w-]+\s*\*/)", css)
    current_subset = None
    for chunk in blocks:
        m = re.match(r"/\*\s*([\w-]+)\s*\*/", chunk.strip())
        if m:
            current_subset = m.group(1)
            continue
        if not chunk.strip():
            continue
        if keep_subsets is not None and current_subset not in keep_subsets:
            continue
        # rewrite each gstatic url in this chunk
        def repl(mo):
            url = mo.group(1)
            fname = url.rsplit("/", 1)[-1]
            dest = os.path.join(FONT_DIR, fname)
            if not os.path.exists(dest):
                n = download(url, dest)
                print(f"  downloaded {fname} ({n} bytes)")
            return f"url(/assets/fonts/{fname})"
        chunk = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", repl, chunk)
        out_lines.append(chunk.strip())
    return "\n".join(out_lines)


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    parts = ["/* Self-hosted fonts. Generated by scripts/selfhost_fonts.py. */\n"]

    print("Fetching Roboto + Roboto Slab ...")
    text_css = fetch(SOURCES["text"])
    parts.append("/* Roboto + Roboto Slab (latin, latin-ext) */")
    parts.append(localize(text_css, keep_subsets=KEEP_SUBSETS))

    print("Fetching Material Icons ...")
    icons_css = fetch(SOURCES["icons"])
    parts.append("\n/* Material Icons */")
    parts.append(localize(icons_css, keep_subsets=None))

    with open(CSS_OUT, "w") as f:
        f.write("\n".join(parts) + "\n")
    print(f"\nWrote {CSS_OUT}")
    print(f"Fonts in {FONT_DIR}: {len(os.listdir(FONT_DIR))} files")


if __name__ == "__main__":
    main()
